ServerEvents.tags('item', event => {
  event.add('c:hidden_from_recipe_viewers', /additionaladditions:rose_gold_(helmet|chestplate|leggings|boots|alloy)/)
  event.add('c:hidden_from_recipe_viewers', /additionaladditions:gilded_netherite_(helmet|chestplate|leggings|boots|sword|axe|pickaxe|shovel|hoe)/)
  event.add('c:hidden_from_recipe_viewers', /additionaladditions:(gold_ring|rope|wrench|copper_patina|patina_block|trident_shard|glow_stick)/)
  event.add("c:hidden_from_recipe_viewers", /biomemakeover:(tadpole_bucket|toad_spawn_egg|tadpole_spawn_egg|icon_item)/)
  event.add("c:hidden_from_recipe_viewers", /bosses_of_mass_destruction:(void_blossom_block|vine_wall|obsidilith_rune|sealed_blackstone|void_blossom)/)
  event.add("c:hidden_from_recipe_viewers", /charm:azalea_(planks|button|door|fence|fence_gate|log|pressure_plate|slab|stairs|trapdoor|wood|sign|barrel|bookshelf|chest|ladder|trapped_chest|bookcase|boat|chest_boat)/)
  event.add("c:hidden_from_recipe_viewers", /charm:(kiln|ebony_barrel|bat_bucket|acacia_barrel|birch_barrel|mangrove_barrel|dark_oak_barrel|jungle_barrel|crimson_barrel|oak_barrel|spruce_barrel|warped_barrel|acacia_chest|acacia_trapped_chest|birch_chest|birch_trapped_chest|crimson_chest|crimson_trapped_chest|dark_oak_chest|dark_oak_trapped_chest|jungle_chest|jungle_trapped_chest|mangrove_chest|mangrove_trapped_chest|oak_chest|oak_trapped_chest|spruce_chest|spruce_trapped_chest|warped_chest|warped_trapped_chest|acacia_ladder|birch_ladder|crimson_ladder|dark_oak_ladder|jungle_ladder|mangrove_ladder|oak_ladder|spruce_ladder|warped_ladder|ebony_chest|ebony_ladder|ebony_trapped_chest|acacia_bookshelf|birch_bookshelf|crimson_bookshelf|dark_oak_bookshelf|jungle_bookshelf|mangrove_bookshelf|oak_bookshelf|spruce_bookshelf|warped_bookshel|totem_of_preserving_holder|stripped_azalea_log|stripped_azalea_wood|atlas|player_pressure_plate|raid_horn|moobloom_spawn_egg|waxed_iron_block)/)
  event.add("c:hidden_from_recipe_viewers", /charm:(white|orange|magenta|light_blue|yellow|lime|pink|gray|light_gray|cyan|purple|blue|brown|green|red|black)_bundle/)
  event.add("c:hidden_from_recipe_viewers", /charm:(exposed_|weathered_|oxidized_|cut_|exposed_cut_|weathered_cut_|oxidized_cut_|waxed_exposed_|waxed_weathered_|waxed_oxidized_|waxed_exposed_cut_|waxed_weathered_cut_|waxed_oxidized_cut_)iron(_slab|_stairs|_block)/)
  event.add("c:hidden_from_recipe_viewers", /charm:(exposed_|weathered_|oxidized_|cut_)iron/)
  event.add("c:hidden_from_recipe_viewers", /charm:(waxed_exposed_|waxed_weathered_|waxed_oxidized_)iron/)
  event.add("c:hidden_from_recipe_viewers", /charm:(exposed_cut_|weathered_cut_|oxidized_cut_)iron/)
  event.add("c:hidden_from_recipe_viewers", /charm:(waxed_exposed_cut_|waxed_weathered_cut_|waxed_oxidized_cut_|waxed_cut_)iron/)
  event.add("c:hidden_from_recipe_viewers", /charm:(waxed_exposed_cut_|waxed_weathered_cut_|waxed_oxidized_cut_|waxed_cut_)iron(_slab|_stairs)/)
  event.add("c:hidden_from_recipe_viewers", /deeperdarker:warden_(helmet|chestplate|leggings|boots|sword|axe|pickaxe|shovel|hoe)/)
  event.add("c:hidden_from_recipe_viewers", /endrem:cryptic_eye/)
  event.add("c:hidden_from_recipe_viewers", /fwaystones:waystone_debugger/)
  event.add("c:hidden_from_recipe_viewers", /summoningrituals:indestructible_altar/)
  event.add("c:hidden_from_recipe_viewers", /wardentools:warden_(helmet|chestplate|leggings|boots|sword|axe|pickaxe|shovel|hoe)/)
  event.add("c:hidden_from_recipe_viewers", /wardentools:heart_of_the_warden|echo_staff|budding_sculk|echo_lantern|echo_cluster|echo_bud|sculk_crystal_block|soul_of_the_warden/)
  event.add("c:hidden_from_recipe_viewers", /wardenloot:warden_heart/)
  event.add("c:hidden_from_recipe_viewers", /supplementaries:(bomb_|bomb_blue_|bomb_spiky_)projectile/)
  event.add("c:hidden_from_recipe_viewers", /supplementaries:present(_white|_orange|_magenta|_light_blue|_yellow|_lime|_pink|_gray|_light_gray|_cyan|_purple|_blue|_brown|_green|_red|_black)/)
  event.add("c:hidden_from_recipe_viewers", /supplementaries:trapped_present(_white|_orange|_magenta|_light_blue|_yellow|_lime|_pink|_gray|_light_gray|_cyan|_purple|_blue|_brown|_green|_red|_black)/)
  event.add("c:hidden_from_recipe_viewers", /supplementaries:present|trapped_present|brass_lantern|sconce_nether_brass|sconce_ender|sconce_glow|sconce_green|copper_lantern|lead_lantern|rope|rope_arrow|bamboo_spikes|bamboo_spikes_tipped|silver_door|silver_trapdoor|lead_door|lead_trapdoor|pancake_disc|placeable_item|checker_vertical_slab|lapis_bricks_vertical_slab|ash_bricks_vertical_slab|stone_tile_vertical_slab|sugar_cube/)
  event.add("c:hidden_from_recipe_viewers", /friendsandfoes:moobloom_spawn_egg/)
  event.add("c:hidden_from_recipe_viewers", /oxidized:rose_gold_(sword|axe|pickaxe|shovel|hoe)/)
  event.add("c:hidden_from_recipe_viewers", /oxidized:copper_nugget/)
  event.add("c:hidden_from_recipe_viewers", /(betterend|betternether):(blackstone_|basalt_|netherrack_|flavolite_|violecite_|sulphuric_rock_|virid_jadestone_|azure_jadestone_|sandy_jadestone_|umbralith_|end_stone_|)furnace/)
  event.add("c:hidden_from_recipe_viewers", /impaled:maelstrom/)
  event.add("c:hidden_from_recipe_viewers", /betternether:(nether_reed|stalagnate|willow|wart|warped|crimson|rubeus|mushroom_fir|anchor_tree|nether_mushroom|nether_sakura)(_composter|_bar_stool|_taburet|_chair|_stool|_ladder|_chest|_crafting_table|_barrel)/)
  event.add("c:hidden_from_recipe_viewers", /betternether:(oak_|spruce_|birch_|jungle_|acacia_|dark_oak_|warped_|crimson_)(taburet|chair|bar_stool)|chest_of_drawers/)
  event.add("c:hidden_from_recipe_viewers", /betternether:(crafting_table_crimson|crafting_table_warped|taburet_cincinnasite|chair_cincinnasite|bar_stool_cincinnasite|cincinnasite_bars|cincinnasite_frame|cincinnasite_anvil|lapis_pile|stalagnate_bowl_mushroom|cincinnasite_forge|stalagnate_bowl_apple)/)
  event.add("c:hidden_from_recipe_viewers", /betterend:(pythadendron_|end_lotus_|mossy_glowshroom_|lacugrove_|tenanea_|helix_tree_|umbrella_tree_|jellyshroom_|lucernia_|dragon_tree_)(chest|composter|crafting_table|barrel)/)
  event.add("c:hidden_from_recipe_viewers", /spelunkery:raw_zinc_nugget/)
  event.add("c:hidden_from_recipe_viewers", /adventurez:spawn_dragon/)
  event.add("c:hidden_from_recipe_viewers", /farmersdelight:tree_bark/)
  event.add("c:hidden_from_recipe_viewers", /betterend:(thallasium_|terminite_|aeternium_)(pickaxe_head|shovel_head|axe_head|hoe_head|sword_blade|sword_handle|forged_plate|anvil|hammer_head)/)
  event.add("c:hidden_from_recipe_viewers", "immersive_weathering:betternether/nether_reed_scales")
  event.add("c:hidden_from_recipe_viewers", "toms_storage:ts.wireless_terminal", "toms_storage:ts.adv_wireless_terminal")
  event.add("c:hidden_from_recipe_viewers", /galosphere:icon_item/)
  event.add("c:hidden_from_recipe_viewers", /_vertical_slab/)
  event.add("c:hidden_from_recipe_viewers", /_trophy/)
  event.add("c:hidden_from_recipe_viewers", /expandeddelight:mac_and_cheese/)
  event.add("c:hidden_from_recipe_viewers", /oxidized:copper_kiln/)
  event.add("c:hidden_from_recipe_viewers", /candlelight:((cobblestone_|sandstone_|stone_bricks_|deepslate_|granite_|end_|mud_|quartz_|red_nether_bricks_)(stove|wood_fired_oven|kitchen_sink)|rose|pancake|tomato_crate|apple_pie_slice|typewriter_copper|typewriter_iron|table|sofa|lamp|chair|drawer|cabinet|sideboard|floorboard|wine_station|cooking_pot|cooking_pan|heart|cooked_beef|(oak_|spruce_|birch_|jungle_|acacia_|dark_oak_|warped_|crimson_|mangrove_)(chair|drawer|cabinet|table))/)
  event.add("c:hidden_from_recipe_viewers", /vinery:(stove|coarse_dirt_slab|dirt_slab|grass_slab|chair|big_table|cooking_pot|dough|table|storage_pot|wood_fired_oven|tomato|apple_pie)/)
  event.add("c:hidden_from_recipe_viewers", /netherdepthsupgrade:soul_sucker_boots/)
  event.add("c:hidden_from_recipe_viewers", /twigs:twigs/)
  event.add("c:hidden_from_recipe_viewers", "variant_bookshelves:block/stripped_bamboo_bookshelf")
  
  event.remove("c:hidden_from_recipe_viewers", /betternether:(nether_reed|stalagnate|willow|wart|warped|crimson|rubeus|mushroom_fir|anchor_tree|nether_mushroom|nether_sakura)_chest_boat/)
  
  event.add("minecraft:wooden_fence_gates", /(betternether|betterend):(nether_reeds_|stalagnate_|willow_|wart_|rubeus_|mushroom_fir_|nether_mushroom_|anchor_tree_|nether_sakura_|mossy_glowshroom_|pythadendron_|end_lotus_|lacugrove_|dragon_tree_|tenanea_|helix_tree_|umbrella_tree_|jellyshroom_|lucernia_)_gate/)
  event.add("minecraft:wooden_fence_gates", /(minecraft|biomemakeover|charm|deeperdarker|ecologics|twigs|vinery|wilderwild|immersive_weathering):(oak_|spruce_|birch_|jungle_|acacia_|dark_oak_|warped_|crimson_|blighted_balsa_|willow_|swamp_cypress_|ancient_oak_|ebony_|echo_|coconut_|walnut_|azalea_|flowering_azalea_|stripped_bamboo_|cherry_|baobab_|cypress_|mangrove_)fence_gate/)
  event.add("minecraft:flowers", /(wilderwild|):(glory_of_the_snow|blue_giant_glory_of_the_snow|pinkglory_of_the_snow|violet_beauty_glory_of_the_snow|alba_glory_of_the_snow)/)
})

ServerEvents.loaded(e => e.server.runCommandSilent('reload'))