ServerEvents.tags('item', event => {
  event.add("c:hidden_from_recipe_viewers", /biomemakeover:(tadpole_bucket|toad_spawn_egg|tadpole_spawn_egg|icon_item)/)
  event.add("c:hidden_from_recipe_viewers", /bosses_of_mass_destruction:(void_blossom_block|vine_wall|obsidilith_rune|sealed_blackstone|void_blossom)/)
  event.add("c:hidden_from_recipe_viewers", /endrem:cryptic_eye/)
  event.add("c:hidden_from_recipe_viewers", /fwaystones:waystone_debugger/)
  event.add("c:hidden_from_recipe_viewers", /supplementaries:(bomb_|bomb_blue_|bomb_spiky_)projectile/)
  event.add("c:hidden_from_recipe_viewers", /supplementaries:(pulley_block|speaker_block|bellows|lock_block|cog_block|rope_arrow_from_display|rope_arrow_create_display|brass_lantern|sconce_nether_brass|sconce_ender|sconce_glow|sconce_green|copper_lantern|lead_lantern|rope|rope_arrow|bamboo_spikes|bamboo_spikes_tipped|silver_door|silver_trapdoor|lead_door|lead_trapdoor|pancake_disc|placeable_item|checker_vertical_slab|lapis_bricks_vertical_slab|ash_bricks_vertical_slab|stone_tile_vertical_slab|sugar_cube)/)
  event.add("c:hidden_from_recipe_viewers", /friendsandfoes:moobloom_spawn_egg/)
  event.add("c:hidden_from_recipe_viewers", /oxidized:rose_gold_(sword|axe|pickaxe|shovel|hoe)/)
  event.add("c:hidden_from_recipe_viewers", /oxidized:(copper_nugget|copper_pulsar)/)
  event.add("c:hidden_from_recipe_viewers", /(betterend|betternether):(blackstone_|basalt_|netherrack_|flavolite_|violecite_|sulphuric_rock_|virid_jadestone_|azure_jadestone_|sandy_jadestone_|umbralith_|end_stone_|)furnace/)
  event.add("c:hidden_from_recipe_viewers", /(betterend|betternether):(_chest)/)
  event.add("c:hidden_from_recipe_viewers", /(betterend):aeternium_|thallasium_|terminite_|crystalite_|leather_wrapped_stick|handle_attachment_smithing_template|leather_handle_attachment_smithing_template|tool_assembly_smithing_template|plate_upgrade_smithing_template|netherite_upgrade_smithing_template/)
  event.add("c:hidden_from_recipe_viewers", /betternether:(nether_reed|stalagnate|willow|wart|warped|crimson|rubeus|mushroom_fir|anchor_tree|nether_mushroom|nether_sakura)(_composter|_bar_stool|_taburet|_chair|_stool|_ladder|_chest|_crafting_table|_barrel|_bookshelf)/)
  event.add("c:hidden_from_recipe_viewers", /betternether:(oak_|spruce_|birch_|jungle_|acacia_|dark_oak_|warped_|crimson_|cherry_|bamboo_|mangrove_)(taburet|chair|bar_stool)|chest_of_drawers/)
  event.add("c:hidden_from_recipe_viewers", /betternether:(crafting_table_crimson|crafting_table_warped|taburet_cincinnasite|chair_cincinnasite|bar_stool_cincinnasite|cincinnasite_bars|cincinnasite_frame|cincinnasite_anvil|lapis_pile|stalagnate_bowl_mushroom|cincinnasite_forge|stalagnate_bowl_apple|bowl_upgrade_smithing_template|flaming_ruby_upgrade_smithing_template|cincinnasite_diamond_upgrade_smithing_template)/)
  event.add("c:hidden_from_recipe_viewers", /betternether:(cincinnasite_)(pickaxe|axe|sword|hoe|shovel|shoes|leggings|chestplate|helmet)(_diamond)/)
  event.add("c:hidden_from_recipe_viewers", /betternether:(flaming_ruby_)(pickaxe|axe|sword|hoe|shovel|boots|leggings|chestplate|helmet)/)
  event.add("c:hidden_from_recipe_viewers", /betterend:(pythadendron_|end_lotus_|mossy_glowshroom_|lacugrove_|tenanea_|helix_tree_|umbrella_tree_|jellyshroom_|lucernia_|dragon_tree_)(chest|composter|crafting_table|barrel|ladder|bookshelf|chair|bar_stool|taburet)/)
  event.add("c:hidden_from_recipe_viewers", /spelunkery:raw_zinc_nugget/)
  event.add("c:hidden_from_recipe_viewers", /adventurez:spawn_dragon/)
  event.add("c:hidden_from_recipe_viewers", /farmersdelight:tree_bark/)
  event.add("c:hidden_from_recipe_viewers", /(ends_delight):_knife/)
  event.add("c:hidden_from_recipe_viewers", /betterend:(thallasium_|terminite_|aeternium_)(pickaxe_head|shovel_head|axe_head|hoe_head|sword_blade|sword_handle|forged_plate|anvil|hammer_head)/)
  //event.add("c:hidden_from_recipe_viewers", "immersive_weathering:betternether/nether_reed_scales")
  event.add("c:hidden_from_recipe_viewers", /_vertical_slab/)
  event.add("c:hidden_from_recipe_viewers", /_trophy/)
  event.add("c:hidden_from_recipe_viewers", /expandeddelight:mac_and_cheese/)
  event.add("c:hidden_from_recipe_viewers", /oxidized:copper_kiln/)
  event.add("c:hidden_from_recipe_viewers", /(candlelight|bakery):((cobblestone_|basalt_|bamboo_|sandstone_|stone_bricks_|deepslate_|granite_|end_|mud_|quartz_|red_nether_bricks_)(stove|wood_fired_oven|kitchen_sink|counter)|rose|pancake|tomato|tomato_seeds|tomato_crate|apple_pie_slice|typewriter_copper|typewriter_iron|table|sofa|lamp|chair|drawer|cabinet|sideboard|floorboard|wine_station|cooking_pot|cooking_pan|heart|cooked_beef|(oak_|spruce_|birch_|jungle_|acacia_|dark_oak_|warped_|crimson_|mangrove_)(chair|drawer|cabinet|table))/)
  event.add("c:hidden_from_recipe_viewers", /vinery:(fermentation_barrel|stove|coarse_dirt_slab|dirt_slab|grass_slab|chair|big_table|cooking_pot|dough|table|storage_pot|wood_fired_oven|tomato|apple_pie)/)
  event.add("c:hidden_from_recipe_viewers", /netherdepthsupgrade:soul_sucker_boots/)
  event.add("c:hidden_from_recipe_viewers", /twigs:(twigs|polished_amethyst|cut_amethyst)/)
  event.add("c:hidden_from_recipe_viewers", /betterend:(elytra_armored|elytra_crystalite)/)
  event.add("c:hidden_from_recipe_viewers", /expandeddelight:(salt_ore|deepslate_salt_ore)/)
  event.add("c:hidden_from_recipe_viewers", /_slab_vert/)
  event.add("c:hidden_from_recipe_viewers", "adventurez:handbook")
  event.add("c:hidden_from_recipe_viewers", /things:(things_almanac|stone_glowstone_fixture|quartz_glowstone_fixture|deepslate_glowstone_fixture)/)
  event.add("c:hidden_from_recipe_viewers", /candlelight:(birch_|oak_|acacia_|spruce_|dark_oak_|jungle_|mangrove_|warped_|crimson_|cherry_|bamboo_)(shelf|big_table|drawer|table|chair|cabinet)/)
  event.add("c:hidden_from_recipe_viewers", /(natures_spirit|handcrafted|bakery|candlelight|vinery):(shelf|whole_pizza|bench|frozen_bench|bread_knife|small_cooking_pot|dough|apple_pie_slice|apple_pie|chocolate_tart_slice|chocolate_tart|side_table|pasta_raw|pizza|pizza_slice|chocolate|jewelry_box|chocolate_box|faucet|gold_ring|letter_open|love_letter_open)/)
  
  event.remove("c:hidden_from_recipe_viewers", /betternether:(nether_reed|stalagnate|willow|wart|warped|crimson|rubeus|mushroom_fir|anchor_tree|nether_mushroom|nether_sakura)_chest_boat|terminite_bulb_|thallasium_bulb_/)
  event.remove("c:bread", "candlelight:cooked_beef")
  event.remove("c:dough", /(bakery|candlelight):dough/)
  event.remove("bakery:dough", /(bakery|candlelight):dough/)

  event.add("minecraft:wooden_fence_gates", /(betternether|betterend):(nether_reeds_|stalagnate_|willow_|wart_|rubeus_|mushroom_fir_|nether_mushroom_|anchor_tree_|nether_sakura_|mossy_glowshroom_|pythadendron_|end_lotus_|lacugrove_|dragon_tree_|tenanea_|helix_tree_|umbrella_tree_|jellyshroom_|lucernia_)_gate/)
  event.add("minecraft:wooden_fence_gates", /(minecraft|biomemakeover|charm|deeperdarker|ecologics|twigs|vinery|wilderwild|immersive_weathering):(oak_|spruce_|birch_|jungle_|acacia_|dark_oak_|warped_|crimson_|blighted_balsa_|willow_|swamp_cypress_|ancient_oak_|ebony_|echo_|coconut_|walnut_|azalea_|flowering_azalea_|stripped_bamboo_|cherry_|baobab_|cypress_|mangrove_)fence_gate/)
  event.add("minecraft:flowers", /(wilderwild):(glory_of_the_snow|blue_giant_glory_of_the_snow|pinkglory_of_the_snow|violet_beauty_glory_of_the_snow|alba_glory_of_the_snow)/)
  event.add("twigs:seashells", "angling:clam","ecologics:seashell")
  event.add("c:leather", "minecraft:rabbit_hide")
  const beds = event.get('handcrafted:fancy_beds').getObjectIds()
  beds.forEach(beds => { 
    {
      event.add('minecraft:beds', beds)
    }
  })
  event.removeAll('biomemakeover:lily_pad')
})


ServerEvents.loaded(e => e.server.runCommandSilent('reload'))